//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section
    {
        public int SectionID { get; set; }
        public byte SectionNum { get; set; }
        public int CourseID { get; set; }
        public int RoomID { get; set; }
        public byte[] Time { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Room Room { get; set; }
    }
}
