
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SchoolManagementSystem.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TimeTable
{

    public int CourseID { get; set; }

    public int SectionID { get; set; }

    public int RoomID { get; set; }

    public int YearID { get; set; }

    public int TimeTableID { get; set; }

    public string TeacherName { get; set; }

    public int UserID { get; set; }



    public virtual Course Course { get; set; }

    public virtual Room Room { get; set; }

    public virtual Section Section { get; set; }

    public virtual Year Year { get; set; }

    public virtual TimeTable TimeTable1 { get; set; }

    public virtual TimeTable TimeTable2 { get; set; }

    public virtual User User { get; set; }

}

}
