//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int ID { get; set; }
        public byte[] Data { get; set; }
        public string Extension { get; set; }
        public int CourseID { get; set; }
        public string FileName { get; set; }
    
        public virtual Course Course { get; set; }
    }
}
