//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystemAPI.Models
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Linq;

    public partial class Announcement
    {
        public SchoolMSEntities ty = new SchoolMSEntities();

        public int AnnounID { get; set; }
        public int CourseID { get; set; }
        public string Announcement1 { get; set; }
        public System.DateTime TimeAnnounced { get; set; }
    
        public virtual Course Course { get; set; }

        private ObservableCollection<Announcement> _AnnoucnRecords;
        public ObservableCollection<Announcement> AllAnnounc
        {
            get
            {
                return _AnnoucnRecords;
            }
            set
            {
                _AnnoucnRecords = value;
            }
        }
        public List<Announcement> GetAll1 ()
        {
            return ty.Announcements.ToList();
        }

        

        public void GetAll ()
        {
            AllAnnounc = new ObservableCollection<Announcement>();
            GetAll1().ForEach(data => AllAnnounc.Add(new Announcement()
            {
                AnnounID = Convert.ToInt32(data.AnnounID),
                CourseID = Convert.ToInt32(data.CourseID),
                Announcement1 = data.Announcement1,
                TimeAnnounced = Convert.ToDateTime(data.TimeAnnounced)

            }));

        }
        public void AddAnnoun ( int CourseID, string Announ, DateTime AnnoTime )
        {

            Announcement anno = new Announcement();
            anno.CourseID = CourseID;
            anno.Announcement1 = Announ;
            anno.TimeAnnounced = AnnoTime;


            ty.Announcements.Add(anno);
            ty.SaveChanges();
            GetAll();

        }

        public void UpdateAnnoun ( int announID, int CourseID, string Announ, DateTime AnnoTime )
        {
            if (CheckAnnounID(AnnounID))
            {
                Announcement anno = (from m in ty.Announcements where m.AnnounID == announID select m).Single();
                anno.AnnounID = announID;
                anno.CourseID = CourseID;
                anno.Announcement1 = Announ;
                anno.TimeAnnounced = AnnoTime;

                ty.SaveChanges();
                GetAll();
            }
            
        }

        public void DeleteAnnoun ( int AnnounID )
        {
            if (CheckAnnounID(AnnounID))
            {
                var deleteanno = ty.Announcements.Where(m => m.AnnounID == AnnounID).Single();
                ty.Announcements.Remove(deleteanno);
                ty.SaveChanges();
                GetAll();
            }
            
        }

        public bool CheckAnnounID ( int AnnounID )
        {

            if (ty.Announcements.Any(o => o.AnnounID == AnnounID))
            {
                return true;
            }
            else
            {
                return false;
            }

        }

    }
}
