//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystemAPI.Models
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Linq;

    public partial class Announcement
    {
        public SchoolMSEntities ty = new SchoolMSEntities();

        public int AnnounID { get; set; }
        public int CourseID { get; set; }
        public string Announcement1 { get; set; }
        public System.DateTime TimeAnnounced { get; set; }
    
        public virtual Course Course { get; set; }

        private ObservableCollection<Announcement> _AnnoucnRecords;
        public ObservableCollection<Announcement> AllAnnounc
        {
            get
            {
                return _AnnoucnRecords;
            }
            set
            {
                _AnnoucnRecords = value;
            }
        }
        public List<Announcement> GetAll1 ()
        {
            return ty.Announcements.ToList();
        }


        public void GetAll ()
        {
            AllAnnounc = new ObservableCollection<Announcement>();
            GetAll1().ForEach(data => AllAnnounc.Add(new Announcement()
            {
                AnnounID = Convert.ToInt32(data.AnnounID),
                CourseID = Convert.ToInt32(data.CourseID),
                Announcement1 = data.Announcement1,
                TimeAnnounced = Convert.ToDateTime(data.TimeAnnounced)

            }));

        }

        public Announcement Get ( int id )
        {
            return ty.Announcements.Find(id);
        }


        public void AddAnnoun ( Announcement newAnnouncement )
        {

            ty.Announcements.Add(newAnnouncement);
            ty.SaveChanges();

        }

        public void UpdateAnnoun ( int announID, Announcement anno )
        {
            var result = (from m in ty.Announcements where m.AnnounID == announID select m).Single();
            if (result != null)
            {
                result.AnnounID = anno.AnnounID;
                result.CourseID = anno.CourseID;
                result.Announcement1 = anno.Announcement1;
                result.TimeAnnounced = anno.TimeAnnounced;

                ty.SaveChanges();

            }

        }

        public void DeleteAnnoun ( int AnnounID )
        {

            var deleteanno = ty.Announcements.Where(m => m.AnnounID == AnnounID).Single();
            ty.Announcements.Remove(deleteanno);
            ty.SaveChanges();
            GetAll();


        }
        

    }
}
