//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystemAPI.Models
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Linq;

    public partial class TimeTable
    {
        public SchoolMSEntities ty = new SchoolMSEntities();

        public int TimeTableID { get; set; }
        public int UserID { get; set; }
        public int CourseID { get; set; }
        public int SectionID { get; set; }
        public string RoomNo { get; set; }
        public int Year { get; set; }
        public string TeacherName { get; set; }
        public string CourseName { get; set; }
        public string Time { get; set; }
        public string CourseCode { get; set; }
        public int SectionNo { get; set; }
        public System.DateTime Examdate { get; set; }

        public virtual Course Course { get; set; }
        public virtual Section Section { get; set; }
        public virtual User User { get; set; }

        private ObservableCollection<TimeTable> _courseRecords;
        public ObservableCollection<TimeTable> AllCourses
        {
            get
            {
                return _courseRecords;
            }
            set
            {
                _courseRecords = value;
            }
        }

        public List<TimeTable> GetAll1 ( int UserID )
        {
            return ty.TimeTables.Where(m => m.UserID == UserID).ToList();
        }


        public TimeTable GetTimeTable ( int TimeTableID )
        {
            return ty.TimeTables
                     .Where(s => s.TimeTableID == TimeTableID)
                     .FirstOrDefault() as TimeTable;
            //var Timetable = ty.TimeTables.FirstOrDefault(y => y.TimeTableID == TimeTableID);
            //return Timetable;

        }


        public void GetAll ( int UserID )
        {
            AllCourses = new ObservableCollection<TimeTable>();
            GetAll1(UserID).ForEach(data => AllCourses.Add(new TimeTable()
            {

                UserID = Convert.ToInt32(data.UserID),
                CourseID = Convert.ToInt32(data.CourseID),
                RoomNo = data.RoomNo,
                Year = data.Year,
                TeacherName = data.TeacherName,
                CourseName = data.CourseName,
                Time = data.Time,
                CourseCode = data.CourseCode,
                SectionNo = data.SectionNo,
                Examdate = Convert.ToDateTime(data.Examdate),
                SectionID = Convert.ToInt32(data.SectionID)


            }));

        }

        public void InsertTimeTable ( TimeTable TTable )
        {

            ty.TimeTables.Add(TTable);
            ty.SaveChanges();

        }

        public void DeleteTimeTable ( int TimeTableID )
        {

            var deleteTimeTables = ty.TimeTables.Where(m => m.TimeTableID == TimeTableID).Single();
            ty.TimeTables.Remove(deleteTimeTables);
            ty.SaveChanges();

        }


    }


}